version: 0.2

env:
  variables:
    GITHUB_TOKEN: "invalid"
    PRESTO_VERSION: "326"
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sed -i "s/PRESTO_VERSION_TBD/$PRESTO_VERSION/" pom.xml
      - mvn -q install
  post_build:
    commands:
      - tools/createRelease.sh $GITHUB_TOKEN ddrinka/presto-password-authenticators-cognito $CODEBUILD_RESOLVED_SOURCE_VERSION $PRESTO_VERSION target presto-password-authenticators-cognito-$PRESTO_VERSION.jar