version: 0.2

env:
  variables:
    PRESTO_VERSION: "326"
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sed -i 's/PRESTO_VERSION_TBD/$PRESTO_VERSION/' pom.xml
      - mvn -q install
artifacts:
  files:
    - target/presto-password-authenticators-cognito-*.jar
  discard-paths: yes
cache:
  paths:
    - /root/.m2/